[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "build"  # ✅ Correct: React outputs to /build inside /client
  functions = "../netlify/functions"  # ⛳ FIX: correct relative path from /client

[functions]
  directory = "../netlify/functions"  # ⛳ Also match here for consistency

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200
