[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "build"  # ✅ NOT client/client/build
  functions = "netlify/functions"

[functions]
directory = "netlify/functions"

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200
