[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "build"
  functions = "netlify/functions"  # ✅ This is relative to base → so client/netlify/functions

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200
