[build]
base = "client"
publish = "client/build"
command = "npm install && npm run build"

[functions]
directory = "netlify/functions"

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200
